- ocamlgraph now requires ocaml 3.10 or higher - graph editor automatically compiles if lablgtk2 is installed - Dot: fixed bug in the parsing of subgraphs (patch by Anne Pacalet) - New function Blocks.after_unserialisation - FAQ improved - comments in *.mli improved

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1679,11 +1679,11 @@ OCAMLVERSION=`$OCAMLC -v | sed -n -e 's|.*version *\(.*\)$|\1|p' `
 echo "ocaml version is $OCAMLVERSION"
 
 case $OCAMLVERSION in
-  0.*|1.*|2.*|3.00*|3.01*|3.02*|3.03*|3.04*|3.05*|3.06*|3.07*)
-        { { echo "$as_me:$LINENO: error: ocamlgraph needs ocaml version 3.08.0 or higher" >&5
-echo "$as_me: error: ocamlgraph needs ocaml version 3.08.0 or higher" >&2;}
+  0.*|1.*|2.*|3.0*)
+        { { echo "$as_me:$LINENO: error: ocamlgraph needs ocaml version 3.10.0 or higher" >&5
+echo "$as_me: error: ocamlgraph needs ocaml version 3.10.0 or higher" >&2;}
    { (exit 1); exit 1; }; };;
-  3.08*)
+  3.10*)
 	FORPACK="";;
   *)
 	FORPACK="-for-pack Graph";;
